kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-nats-box-1
  namespace: test
  labels:
    app: my-nats-box
    app.kubernetes.io/managed-by: Helm
    chart: nats-0.19.4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nats-box
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nats-box
    spec:
      containers:
        - name: nats-box
          image: 'natsio/nats-box:0.13.3'
          command:
            - tail
            - '-f'
            - /dev/null
          env:
            - name: NATS_URL
              value: my-nats
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
