apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: demo-privileged
  namespace: gatekeeper-system
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    namespaces: ["gatekeeper-system"]
  location: "spec.containers[name:daprd].securityContext.runAsNonRoot"
  parameters:
    assign:
      value: true