name: create_tag
on: 
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  create_tag:
    name: "Create tag"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    # - name: "Set release tag"
    #   run: |
    #     # RELEASE_TAG=$(echo "${{ github.event.head_commit.message }}" | grep -o 'v[^ ,]\+' | sed -n '1p')
    #     # echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
    #     echo "base ref ${{ github.event.base_ref }}"
    #     echo "ref ${{ github.event.ref }}"
    #     echo "base ref ${{ github.event.pull_request.merged }}"
    #     echo "tag ${{ toJson(github.event.pull_request.labels.*.name) }}"
    #     x=${{ toJson(github.event.pull_request.labels.*.name) }}
    #     echo "$x"
    #     echo "$x[0]"
    #     echo "$x[1]"
    #     echo "${x[0]}"
    #     echo "${x[1]}"
    
    # - name: Check out code
    #   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.2

    # - uses: rickstaa/action-create-tag@v1.6.4
    #   id: "tag_create"
    #   with:
    #     tag: ${{ env.RELEASE_TAG }}
    #     tag_exists_error: false
