name: create_tag
on: 
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  create_tag:
    name: "Create tag"
    runs-on: ubuntu-22.0 4
    if: github.event.pull_request.merged == true
    steps:
    - name: "Set release tag"
      run: |
        # RELEASE_TAG=$(echo "${{ github.event.head_commit.message }}" | grep -o 'v[^ ,]\+' | sed -n '1p')
        # echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
        echo "base ref ${{ github.event.base_ref }}"
        echo "ref ${{ github.event.ref }}"
        echo "base ref ${{ github.event.pull_request.merged }}"
        echo "tag ${{ github.event.pull_request.labels.[0].name }}"
        echo "tag ${{ github.event.pull_request.labels.[1].name }}"
    
    # - name: Check out code
    #   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3.5.2

    # - uses: rickstaa/action-create-tag@v1.6.4
    #   id: "tag_create"
    #   with:
    #     tag: ${{ env.RELEASE_TAG }}
    #     tag_exists_error: false
